Repository to-tasty/toTasty-front, pull requests merged in 2025-08, with the labels that each got.

#189 Refactor/#188-모임 작성 취소 시 뒤로가기 추가
  src/widgets/post-meeting/PostMeetingView.tsx
Labels: refactor 🔨

#204 feat: 모임 참여 추가/삭제 기능 구현 및 적용
  src/features/meetings/api/cancelJoin.ts
  src/features/meetings/api/joinMeeting.ts
  src/features/meetings/index.ts
  src/features/meetings/model/hook/useCancelJoinMutation.ts
  src/features/meetings/model/hook/useJoinMeetingMutation.ts
  src/features/meetings/model/types.ts
  src/views/meetings/detail/MeetingDetailPage.tsx
Labels: feature ✨

#209 fix: ReviewList 필드명 content -> reviews로 변경하여 서버 응답과 일치
  src/entities/reviews/model/types.ts
Labels: bugfix 🐞

#213 feat: 서버 응답 DTO 변경에 따라 ReviewContent에 reviewDate 필드 추가
  src/entities/reviews/model/types.ts
Labels: feature ✨

#214 Refactor/#205 상세페이지 footer 버튼 action 및 기능 추가/수정
  src/views/meetings/detail/MeetingDetailPage.tsx
  src/views/meetings/post/MeetingPostPage.tsx
  src/widgets/detail-meeting/MeetingDetailFooter.tsx
  src/widgets/detail-meeting/model/actions.ts
  src/widgets/detail-meeting/model/getVisibleActions.ts
  src/widgets/detail-meeting/model/hook/index.ts
  src/widgets/detail-meeting/model/hook/useConfirm.tsx
  src/widgets/detail-meeting/model/hook/useNowTick.ts
  src/widgets/detail-meeting/model/hook/useStickyFooter.tsx
  src/widgets/detail-meeting/model/types.ts
  src/widgets/detail-meeting/ui/ActionButtons.tsx
  src/widgets/post-meeting/PostMeetingForm.tsx
  src/widgets/post-meeting/model/validationSchema.ts
Labels: refactor 🔨

#218 Bugfix/#217 잔버그 수정
  src/entities/homeMeetingCard/ui/dummyCardArea.tsx
  src/views/login/LoginPage.tsx
Labels: bugfix 🐞

#251 Refactor/#249 tailwind 전체 정리
  src/app/home/Container.tsx
  src/app/layout.tsx
  src/app/my-page/layout.tsx
  src/entities/homeMeetingCard/model/homeMeetingCard.keys.ts
  src/entities/homeMeetingCard/ui/dummyCardArea.tsx
  src/entities/homeMeetingCard/ui/favoriteMeetingCardArea.tsx
  src/entities/homeMeetingCard/ui/newMeetingCardArea.tsx
  src/entities/homeMeetingCard/ui/popularMeetingCardArea.tsx
  src/entities/homeMeetingCard/ui/wishlistCardArea.tsx
  src/shared/constants/types.ts
  src/shared/lib/datetimeFormat.ts
  src/views/home/HomePage.tsx
  src/widgets/find-meeting/FindMeetingHeader.tsx
  src/widgets/find-meeting/FindMeetingList.tsx
  src/widgets/find-meeting/model/hooks/useFilterBtnStore.ts
  src/widgets/find-meeting/model/types.ts
  src/widgets/find-meeting/ui/FindMeetingCard.tsx
  src/widgets/find-meeting/ui/FindMeetingCardRow.tsx
  src/widgets/find-meeting/ui/FindMeetingFilterBtns.tsx
  src/widgets/mypage-tabs/ui/MyMeetingsCardRow.tsx
  src/widgets/mypage-tabs/ui/MyPageTabs.tsx
  src/widgets/navigation-bar/ui/LoginButton.tsx
  src/widgets/navigation-bar/ui/NavigationTabs.tsx
  src/widgets/navigation-bar/ui/UserDropdown.tsx
  src/widgets/profile-card/UserProfileCard.tsx
  src/widgets/reviews/ReviewDetail.tsx
  src/widgets/reviews/ui/ReviewImgCard.tsx
Labels: refactor 🔨
